// <auto-generated />
using System;
using GoTravnikApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoTravnikApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231113170340_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoTravnikApi.Models.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Accommodation", (string)null);
                });

            modelBuilder.Entity("GoTravnikApi.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Activity", (string)null);
                });

            modelBuilder.Entity("GoTravnikApi.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Attraction", (string)null);
                });

            modelBuilder.Entity("GoTravnikApi.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("GoTravnikApi.Models.FoodAndDrink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("FoodAndDrink", (string)null);
                });

            modelBuilder.Entity("GoTravnikApi.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("XCoordinate")
                        .HasColumnType("float");

                    b.Property<double>("YCoordinate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("GoTravnikApi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("GoTravnikApi.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int?>("AttractionId")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodAndDrinkId")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("TextComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AttractionId");

                    b.HasIndex("EventId");

                    b.HasIndex("FoodAndDrinkId");

                    b.HasIndex("PostId");

                    b.ToTable("Rating", (string)null);
                });

            modelBuilder.Entity("GoTravnikApi.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int?>("AttractionId")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodAndDrinkId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AttractionId");

                    b.HasIndex("EventId");

                    b.HasIndex("FoodAndDrinkId");

                    b.HasIndex("PostId");

                    b.ToTable("Subcategory", (string)null);
                });

            modelBuilder.Entity("GoTravnikApi.Models.Accommodation", b =>
                {
                    b.HasOne("GoTravnikApi.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Activity", b =>
                {
                    b.HasOne("GoTravnikApi.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Attraction", b =>
                {
                    b.HasOne("GoTravnikApi.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Event", b =>
                {
                    b.HasOne("GoTravnikApi.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GoTravnikApi.Models.FoodAndDrink", b =>
                {
                    b.HasOne("GoTravnikApi.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Post", b =>
                {
                    b.HasOne("GoTravnikApi.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Rating", b =>
                {
                    b.HasOne("GoTravnikApi.Models.Accommodation", null)
                        .WithMany("Ratings")
                        .HasForeignKey("AccommodationId");

                    b.HasOne("GoTravnikApi.Models.Activity", null)
                        .WithMany("Ratings")
                        .HasForeignKey("ActivityId");

                    b.HasOne("GoTravnikApi.Models.Attraction", null)
                        .WithMany("Ratings")
                        .HasForeignKey("AttractionId");

                    b.HasOne("GoTravnikApi.Models.Event", null)
                        .WithMany("Ratings")
                        .HasForeignKey("EventId");

                    b.HasOne("GoTravnikApi.Models.FoodAndDrink", null)
                        .WithMany("Ratings")
                        .HasForeignKey("FoodAndDrinkId");

                    b.HasOne("GoTravnikApi.Models.Post", null)
                        .WithMany("Ratings")
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Subcategory", b =>
                {
                    b.HasOne("GoTravnikApi.Models.Accommodation", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("AccommodationId");

                    b.HasOne("GoTravnikApi.Models.Activity", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("ActivityId");

                    b.HasOne("GoTravnikApi.Models.Attraction", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("AttractionId");

                    b.HasOne("GoTravnikApi.Models.Event", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("EventId");

                    b.HasOne("GoTravnikApi.Models.FoodAndDrink", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("FoodAndDrinkId");

                    b.HasOne("GoTravnikApi.Models.Post", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Accommodation", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Activity", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Attraction", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Event", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("GoTravnikApi.Models.FoodAndDrink", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("GoTravnikApi.Models.Post", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
